from .models import CapabilityDomain, ConsentLevel, ActionType, ActionVerb

# 21 capability domain blueprints distilled from startup architectures (per paper)
DOMAINS = [
    CapabilityDomain(
        name="app_fabrication",
        intent_patterns=["build", "landing page", "create app", "website", "web app"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Generate application code", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Write code to file", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.SHELL, "verb": ActionVerb.EXECUTE, "description": "Deploy application", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["code_execution", "file_access"],
        consent_level=ConsentLevel.STANDARD,
        audience="both",
        source_startups=["Vercel", "Replit"],
    ),
    CapabilityDomain(
        name="growth_marketing",
        intent_patterns=["email campaigns", "marketing", "newsletter", "growth"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Set up email template", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Configure email service", "consent": ConsentLevel.ELEVATED},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Create campaign schedule", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Write campaign config", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["network", "file_access"],
        consent_level=ConsentLevel.ELEVATED,
        audience="enterprise",
        source_startups=["Mailchimp", "HubSpot"],
    ),
    CapabilityDomain(
        name="document_intelligence",
        intent_patterns=["document", "pdf", "extract", "summarize file", "contract"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Read document", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Extract information", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="both",
        source_startups=["DocuSign", "Notion"],
    ),
    CapabilityDomain(
        name="knowledge_graph",
        intent_patterns=["knowledge graph", "relationships", "entities", "graph"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Extract entities", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Write graph data", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["code_execution", "file_access"],
        consent_level=ConsentLevel.STANDARD,
        audience="enterprise",
        source_startups=["Memgraph", "Neo4j"],
    ),
    CapabilityDomain(
        name="finance_ops",
        intent_patterns=["invoice", "payment", "expense", "budget", "finance"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Compute financial summary", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Submit payment", "consent": ConsentLevel.NEVER},
        ],
        required_capabilities=["network", "code_execution"],
        consent_level=ConsentLevel.NEVER,
        audience="enterprise",
        source_startups=["Stripe", "Brex"],
    ),
    CapabilityDomain(
        name="computer_use",
        intent_patterns=["click", "open app", "screenshot", "browse", "automation"],
        execution_grammar=[
            {"action_type": ActionType.SHELL, "verb": ActionVerb.EXECUTE, "description": "Launch process", "consent": ConsentLevel.ELEVATED},
            {"action_type": ActionType.APP, "verb": ActionVerb.EXECUTE, "description": "Send UI action", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["shell", "desktop"],
        consent_level=ConsentLevel.ELEVATED,
        audience="personal",
        source_startups=["Anthropic", "OpenAI"],
    ),
    CapabilityDomain(
        name="realtime_web",
        intent_patterns=["realtime", "websocket", "live", "streaming"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Generate realtime server", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.SHELL, "verb": ActionVerb.EXECUTE, "description": "Start server", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["code_execution", "shell"],
        consent_level=ConsentLevel.ELEVATED,
        audience="both",
        source_startups=["Supabase", "Firebase"],
    ),
    CapabilityDomain(
        name="voice_interface",
        intent_patterns=["voice", "audio", "transcribe", "speech"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Read audio file", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Transcribe audio", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="both",
        source_startups=["ElevenLabs", "AssemblyAI"],
    ),
    CapabilityDomain(
        name="data_analysis",
        intent_patterns=["analyze", "chart", "dataset", "csv", "statistics"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Load dataset", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Run analysis", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Write report", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="both",
        source_startups=["Hex", "Jupyter"],
    ),
    CapabilityDomain(
        name="career_agent",
        intent_patterns=["resume", "job", "cover letter", "interview"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Read resume", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Generate tailored content", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Save output", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="personal",
        source_startups=["LinkedIn", "Grammarly"],
    ),
    CapabilityDomain(
        name="physical_tasks",
        intent_patterns=["delivery", "shipping", "logistics", "inventory"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Plan route", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Book delivery", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["network", "code_execution"],
        consent_level=ConsentLevel.ELEVATED,
        audience="enterprise",
        source_startups=["Uber", "Doordash"],
    ),
    CapabilityDomain(
        name="formal_verification",
        intent_patterns=["verify", "proof", "formal", "theorem", "correctness"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Read specification", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Run proof check", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["code_execution", "file_access"],
        consent_level=ConsentLevel.STANDARD,
        audience="enterprise",
        source_startups=["Certora", "Galois"],
    ),
    CapabilityDomain(
        name="agent_identity",
        intent_patterns=["identity", "profile", "persona", "sign in"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Load identity", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Authenticate", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["network", "file_access"],
        consent_level=ConsentLevel.ELEVATED,
        audience="both",
        source_startups=[["Clerk", "Auth0"]],
    ),
    CapabilityDomain(
        name="autonomous_payments",
        intent_patterns=["pay", "transfer", "payroll", "autonomous payment"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Verify payment details", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Execute payment", "consent": ConsentLevel.NEVER},
        ],
        required_capabilities=["network", "code_execution"],
        consent_level=ConsentLevel.NEVER,
        audience="enterprise",
        source_startups=[["Ripple", "Gusto"]],
    ),
    CapabilityDomain(
        name="content_recall",
        intent_patterns=["remember", "find note", "recall", "search history"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Query memory index", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Retrieve stored memory", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="both",
        source_startups=[["Mem0", "Graphiti"]],
    ),
    CapabilityDomain(
        name="property_ops",
        intent_patterns=["real estate", "property", "lease", "maintenance"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Analyze listing", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Contact owner", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["network", "code_execution"],
        consent_level=ConsentLevel.ELEVATED,
        audience="enterprise",
        source_startups=[["Zillow", "Appfolio"]],
    ),
    CapabilityDomain(
        name="comms_coverage",
        intent_patterns=["summarize messages", "catch up", "chat summary", "communications"],
        execution_grammar=[
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Fetch messages", "consent": ConsentLevel.ELEVATED},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Summarize threads", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["network", "code_execution"],
        consent_level=ConsentLevel.ELEVATED,
        audience="both",
        source_startups=[["Slack", "Discord"]],
    ),
    CapabilityDomain(
        name="visual_generation",
        intent_patterns=["image", "generate image", "diagram", "visual"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Generate prompt", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.NETWORK, "verb": ActionVerb.REQUEST, "description": "Request image generation", "consent": ConsentLevel.ELEVATED},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Save image", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["network", "code_execution", "file_access"],
        consent_level=ConsentLevel.ELEVATED,
        audience="both",
        source_startups=[["Midjourney", "Stable Diffusion"]],
    ),
    CapabilityDomain(
        name="log_compression",
        intent_patterns=["compress logs", "log archive", "cleanup logs"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Read logs", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Compress logs", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.FILE, "verb": ActionVerb.WRITE, "description": "Write archive", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="enterprise",
        source_startups=[["Datadog", "Grafana"]],
    ),
    CapabilityDomain(
        name="inference_optimization",
        intent_patterns=["optimize", "quantization", "distill", "faster model"],
        execution_grammar=[
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Profile model", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.SHELL, "verb": ActionVerb.EXECUTE, "description": "Run optimization", "consent": ConsentLevel.ELEVATED},
        ],
        required_capabilities=["code_execution", "shell"],
        consent_level=ConsentLevel.ELEVATED,
        audience="enterprise",
        source_startups=[["Fireworks", "Together AI"]],
    ),
    CapabilityDomain(
        name="agent_observability",
        intent_patterns=["monitor", "observability", "trace", "debug agent"],
        execution_grammar=[
            {"action_type": ActionType.FILE, "verb": ActionVerb.READ, "description": "Read telemetry", "consent": ConsentLevel.STANDARD},
            {"action_type": ActionType.CODE, "verb": ActionVerb.EVALUATE, "description": "Detect anomalies", "consent": ConsentLevel.STANDARD},
        ],
        required_capabilities=["file_access", "code_execution"],
        consent_level=ConsentLevel.STANDARD,
        audience="enterprise",
        source_startups=[["Langfuse", "Langsmith"]],
    ),
]


def get_domain_registry():
    return {d.name: d for d in DOMAINS}
